version: "3.7"
services:
  doodle_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

